title:    Anu Shrestha # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring data scientist with good background on software development, multiple research works pursued on data science and machine learning fields, keen interest in the latest developments in technology to learn, implement and improve the knowledge and skills for data processing, visualization, modeling, and analysis.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/anu-shrestha-1286118b"/>View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
