title:    Anu Shrestha # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Ph.D. student in the Department of Computer Science and Engineering at Boise State University. 
  I work under the supervision of Dr. Francesca Spezzano in the Data-driven Security lab. 
  My research focuses on characterizing and mitigating misinformation in social media and the web using social network analysis, machine learning,
  deep learning, and natural language processing. As the information in social media and web sources can be truthful, falsified, or just an opinion of the writer, understanding the phenomenon of misinformation is imperative, especially since users are acting not only as consumers but also as information creators, influencers, and spreaders. I have been working to address challenging issues such as, profiling fake news spreaders, understanding the factors that influence humans when assessing the reliability of the information, and identifying trustworthy entities in the information ecosystem both in social media and review based platforms.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/anu-shrestha-1286118b"/>View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
